workflows:
  ios-release:
    name: iOS Release
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

    scripts:
      - name: Flutter packages
        script: flutter pub get

      - name: iOS build (no codesign)
        script: flutter build ios --release --no-codesign

    artifacts:
      - build/ios/iphoneos/Runner.app
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/*.aab

    publishing:
      email:
        recipients:
          - marcel.kovacs07@gmail.com
