workflows:
  ios_testflight:
    name: iOS Tests + TestFlight
    max_build_duration: 90
    instance_type: mac_mini_m2

    integrations:
      app_store_connect: appstore

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: "com.pecazom.app"

    scripts:
      - name: Flutter doctor
        script: flutter doctor -v
      - name: Get packages
        script: flutter pub get
      - name: Run tests
        script: flutter test
      - name: Install CocoaPods
        script: |
          cd ios
          pod install
          cd ..
      - name: Build IPA for App Store
        script: flutter build ipa --release

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
