// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqhLp2Slm1hcy_cNghBJCO05lCfGChdZw',
    appId: '1:355527384626:web:412bece750d642ae4ee62b',
    messagingSenderId: '355527384626',
    projectId: 'fishingapp-89432',
    authDomain: 'fishingapp-89432.firebaseapp.com',
    storageBucket: 'fishingapp-89432.firebasestorage.app',
    measurementId: 'G-RJZP8WC5HP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQuaZG6TYZ8r1R3ypqa1cWq_dlQzraOCI',
    appId: '1:355527384626:android:797d377279b5e8bc4ee62b',
    messagingSenderId: '355527384626',
    projectId: 'fishingapp-89432',
    storageBucket: 'fishingapp-89432.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDe3VJmr7R3ZvwRrebeCjE6oz93GkRl99U',
    appId: '1:355527384626:ios:934e6fbc3bfb26de4ee62b',
    messagingSenderId: '355527384626',
    projectId: 'fishingapp-89432',
    storageBucket: 'fishingapp-89432.firebasestorage.app',
    iosBundleId: 'com.example.fishingAppNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDe3VJmr7R3ZvwRrebeCjE6oz93GkRl99U',
    appId: '1:355527384626:ios:934e6fbc3bfb26de4ee62b',
    messagingSenderId: '355527384626',
    projectId: 'fishingapp-89432',
    storageBucket: 'fishingapp-89432.firebasestorage.app',
    iosBundleId: 'com.example.fishingAppNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqhLp2Slm1hcy_cNghBJCO05lCfGChdZw',
    appId: '1:355527384626:web:008e0fb0f2cc59664ee62b',
    messagingSenderId: '355527384626',
    projectId: 'fishingapp-89432',
    authDomain: 'fishingapp-89432.firebaseapp.com',
    storageBucket: 'fishingapp-89432.firebasestorage.app',
    measurementId: 'G-VZ0DPHW3KZ',
  );

}